const fs = require('fs');

const text = fs.readFileSync('exam_2_raw.txt', 'utf-8');

const qRegex = /(?:\[\d+\/\d+\/\d+\s+[^\]]+\]\s*.*:\s*)?(\d+)\.\s+([\s\S]*?)(?=(?:\[\d+\/\d+\/\d+\s+[^\]]+\]\s*.*:\s*)?\d+\.\s+|$)/g;

let match;
const questions = [];

// Passages to attach
const passage11 = `Passage: Renewable energy sources play a crucial role in the transition to a more sustainable and 
environmentally friendly energy system. Solar energy, for instance, is harnessed through the use 
of photovoltaic cells that convert sunlight directly into electricity. Wind energy is generated by 
harnessing the kinetic energy of moving air through wind turbines. These sources of energy are 
considered cleaner alternatives to fossil fuels, as they produce little to no greenhouse gas 
emissions during operation.
One challenge to utilizing renewable energy is its intermittency. Solar power generation is 
dependent on sunlight availability, which varies with weather conditions and the time of day. 
Wind power generation relies on consistent wind patterns, which may not always be present. To 
address this issue, energy storage systems like batteries are used to store excess energy generated 
during peak production periods for use during low production periods.
Renewable energy technologies have seen significant advancements in recent years, leading to 
increased efficiency and cost-effectiveness. As a result, many countries have set renewable 
energy targets to reduce their reliance on non-renewable sources such as coal, oil, and natural 
gas. Governments and industries worldwide are investing in research and infrastructure to further 
develop and integrate renewable energy into their energy portfolios.\n\n`;

const passage36 = `Passage: The human digestive system is a complex process that involves breaking down food 
into nutrients that can be absorbed by the body. It starts in the mouth, where enzymes begin to 
break down carbohydrates. The food then travels through the esophagus to the stomach, where 
acids and enzymes further break down proteins and other components. The small intestine is 
responsible for nutrient absorption, while the large intestine absorbs water and forms waste into 
feces for elimination.\n\n`;

while ((match = qRegex.exec(text)) !== null) {
  let numStr = match[1];
  let originalNumber = parseInt(numStr);
  let mappedNumber = 0;

  if (originalNumber >= 61 && originalNumber <= 80) {
    mappedNumber = originalNumber - 60;
  } else if (originalNumber >= 1 && originalNumber <= 40) {
    mappedNumber = originalNumber + 20;
  } else {
    // skip e.g. "4.gly" if it parses as 4 (Wait, 4.gly is original 4, mapped 24, let's keep it if it fits)
    continue; 
  }

  // Some false positives? Let's assume the regex works mostly. 
  // Wait, original 4 is "4.gly\nC. eathe current system..." Let's allow it through, since it falls in 1..40.
  
  let block = match[2].trim();
  
  let prompt = "";
  let options = [];
  let answer = "";
  let explanation = "";

  let answerMatch = block.match(/Answer\s+([A-D])(?:\.|)\s*(.*)?/i);
  if (!answerMatch) {
    answerMatch = block.match(/Answer\s*\n\s*([A-E])(?:\.|)\s*(.*)?/i);
  }
  
  let explanationMatch = block.match(/Explanation\s+([\s\S]*)/i);
  
  if (answerMatch) {
    answer = answerMatch[1].toUpperCase();
  }
  if (explanationMatch) {
    explanation = explanationMatch[1].trim();
  } else {
     explanation = "No explanation.";
  }
  
  let promptAndOpts = block;
  let ansIdx = block.match(/Answer/i);
  if (ansIdx) {
    promptAndOpts = block.substring(0, ansIdx.index).trim();
  }

  let optAIdx = promptAndOpts.match(/\nA\.\s/);
  if (!optAIdx) optAIdx = promptAndOpts.match(/\nA\)\s/);
  
  if (optAIdx) {
    prompt = promptAndOpts.substring(0, optAIdx.index).trim();
    let optsText = promptAndOpts.substring(optAIdx.index).trim();
    
    let optA = "", optB = "", optC = "", optD = "", optE = "";
    
    let aMatch = optsText.match(/A[\.\)]\s+([\s\S]*?)(?=\nB[\.\)]|$)/);
    let bMatch = optsText.match(/B[\.\)]\s+([\s\S]*?)(?=\nC[\.\)]|$)/);
    let cMatch = optsText.match(/C[\.\)]\s+([\s\S]*?)(?=\nD[\.\)]|$)/);
    let dMatch = optsText.match(/D[\.\)]\s+([\s\S]*?)(?=\nE[\.\)]|$)/);
    let eMatch = optsText.match(/E[\.\)]\s+([\s\S]*?)$/);
    
    if (aMatch) optA = aMatch[1].trim();
    if (bMatch) optB = bMatch[1].trim();
    if (cMatch) optC = cMatch[1].trim();
    if (dMatch) optD = dMatch[1].trim();
    if (eMatch) optE = eMatch[1].trim();
    
    const parsedOptions = [
      { key: "A", text: optA, isCorrect: answer === "A" },
      { key: "B", text: optB, isCorrect: answer === "B" },
      { key: "C", text: optC, isCorrect: answer === "C" },
      { key: "D", text: optD, isCorrect: answer === "D" }
    ];
    if (optE) {
        parsedOptions.push({ key: "E", text: optE, isCorrect: answer === "E" });
    }
    
    // Add passages
    if (originalNumber === 11) {
        prompt = passage11 + prompt;
    } else if (originalNumber === 36) {
        prompt = passage36 + prompt;
    }

    questions.push({
      key: `cabin-exam-2-q${mappedNumber}`,
      mappedNumber: mappedNumber,
      topicSlug: "exam 2",
      type: "multiple_choice",
      prompt: prompt,
      explanation: explanation,
      options: parsedOptions.filter(o => o.text !== "")
    });
  } else {
    console.log("No options found for mapped Q" + mappedNumber + " (original Q" + originalNumber + ")");
  }
}

// Sort questions by their mapped number
questions.sort((a, b) => a.mappedNumber - b.mappedNumber);

// Remove mappedNumber from final output
const finalQuestions = questions.map(q => {
  const { mappedNumber, ...rest } = q;
  return rest;
});

const payload = {
  questionBank: {
    key: "cabin-exam-bank-2",
    slug: "cabin-exam-2",
    title: "Cabin Crew Exam 2 Bank",
    description: "Grammar, Reading, Sentence Completion",
    departmentCode: "CABIN"
  },
  examSet: {
    key: "cabin-exam-set-2",
    slug: "cabin-exam-2",
    title: "Exam 2",
    description: "Cabin Crew Exam 2",
    departmentCode: "CABIN",
    topicSlug: "exam 2",
    mode: "mock",
    durationMinutes: 90,
    published: true
  },
  questions: finalQuestions
};

fs.writeFileSync('cabin-exam-2.json', JSON.stringify(payload, null, 2));
console.log('Wrote cabin-exam-2.json with', finalQuestions.length, 'questions.');
